AttributeError: read Unresolved
AttributeError continues. Bringing the script files together didn't work. Assigning the PIL to a variable didn't work. image.load() didn't work

Next options:
1) Create the images and document at the same time
2) Change from a dictionary to a list <https://stackoverflow.com/questions/47885897/storing-multiple-image-files-in-a-dictionary>